#[cfg(test)]
mod tests;

// This is auto generated by prost from the given protocol buffers
pub mod block_exchange_protocol {
    // Put the generated rust file in the out directory in target during build
    include!(concat!(env!("OUT_DIR"), "/BEP.protobufs.rs"));
}
